module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats Festival',
    'Village Concert',
    'Canyon Tea Dance',
    'Pond Event',
    'Group Event',
    'Horse Festival',
    'Ghost Town Concert',
    'Camp Fest',
    'Dispersed Fest',
    'Backcountry Fest',
    'River Event',
    'Creek Event',
    'Creekside Event',
    'Bay Event',
    'Spring Event',
    'Bayshore Fest',
    'Sands Fest',
    'Mule Concert',
    'Hunting Fest',
    'Cliffs Concert',
    'Hollow Concert'
]